### PR TITLE
ethermint formula

### PR DESCRIPTION
**Pull request by ramilexe**
```
make
get_vendor_deps

go get github.com/karalabe/xgo github.com/Masterminds/glide honnef.co/go/tools/cmd/megacheck github.com/alecthomas/gometalinter
--> Running glide install
[ERROR]	$GOPATH is not set.
make: *** [get_vendor_deps] Error 1
```

### CODE REVIEW

**Comment by ramilexe** [comment]
@adrianbrink could you check this formula?
does it work on macOS?

**Comment by adrianbrink** [comment]
The formula doesn't work on macOS.

**Comment by ramilexe** [comment]
Does tendermint formula work? Or the same error with $GOPATH?

**Comment by ramilexe** [comment]
@adrianbrink fixed. Ready to merge

**Pull request merged**
